### ISSUE TITLE
Possible issue with commit properties

### ISSUE THREAD

**Issue by valeriocos** [SOM-Research/Gitana#11]
File "/home/recerca/Gitana/extractor/cvs/git/git2db_extract_reference.py", line 295, in analyse_commit
   authored_date = datetime.fromtimestamp(self.querier.get_commit_property(commit, "authored_date")).strftime("%Y-%m-%d %H:%M:%S")
TypeError: a float is required
reported by @jlcanovas

**Comment by valeriocos** [comment]
Although difficult to replicate, the problem seems to be related to GitPython that may fail when retrieving commits with a large commit message. The problem should have been fixed in 5e61ef4c516dfb086411e27bd4399c1f9dc54984

**Comment by jlcanovas** [comment]
Ok! I'll launch again the process to see how it evolves! 

I'll report here, thks!

**Comment by jlcanovas** [comment]
After pulling the last version, I get this error:

<pre>
2016-10-20 11:13:59:ERROR:Git2DbUpdate failed
Traceback (most recent call last):
  File "/home/recerca/Gitana/extractor/cvs/git/git2db_update.py", line 144, in update
    self.update_repo(repo_id, self.get_import_type(repo_id))
  File "/home/recerca/Gitana/extractor/cvs/git/git2db_update.py", line 127, in update_repo
    self.delete_last_commit_info(repo_id)
  File "/home/recerca/Gitana/extractor/cvs/git/git2db_update.py", line 120, in delete_last_commit_info
    self.dao.delete_commit(last_commit_id, repo_id)
  File "/home/recerca/Gitana/extractor/cvs/git/git_dao.py", line 122, in delete_commit
    cursor.execute(query, arguments)
  File "/usr/lib/python2.7/site-packages/mysql/connector/cursor.py", line 503, in execute
    psub = _ParamSubstitutor(self._process_params(params))
  File "/usr/lib/python2.7/site-packages/mysql/connector/cursor.py", line 386, in _process_params
    "Failed processing format-parameters; %s" % err)
ProgrammingError: Failed processing format-parameters; Python 'tuple' cannot be converted to a MySQL type
</pre>

The process tries to start but suddenly dies. Only one log file is produced so it seems it does not start to analyze references.

**Comment by valeriocos** [comment]
sorry for that, it was an error introduced in a recent code refactoring. That error is fixed in f6c97243b8765a055fdf06a82e833e3fe2431790

**Comment by jlcanovas** [comment]
After trying with the last modifications, the extraction process was having problems connecting to the database. As this issue does not seem to be related with the tool, I close it.
