### ISSUE TITLE
add PyJWT to install_requires.

### ISSUE THREAD

**Issue by mopuru-murali** [SOM-Research/Gitana#15]
>>> from gitana import Gitana
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/dbc/blr-dbc301/mmopuru/anaconda2/lib/python2.7/site-packages/gitana-1.0-py2.7.egg/gitana/gitana.py", line 19, in <module>
    from importers.issue_tracker.github.issue2db_extract_main import GitHubIssue2DbMain
  File "/dbc/blr-dbc301/mmopuru/anaconda2/lib/python2.7/site-packages/gitana-1.0-py2.7.egg/importers/issue_tracker/github/issue2db_extract_main.py", line 8, in <module>
    from issue2db_extract_issue import GitHubIssue2Db
  File "/dbc/blr-dbc301/mmopuru/anaconda2/lib/python2.7/site-packages/gitana-1.0-py2.7.egg/importers/issue_tracker/github/issue2db_extract_issue.py", line 8, in <module>
    from querier_github import GitHubQuerier
  File "/dbc/blr-dbc301/mmopuru/anaconda2/lib/python2.7/site-packages/gitana-1.0-py2.7.egg/importers/issue_tracker/github/querier_github.py", line 5, in <module>
    from github import Github
  File "/dbc/blr-dbc301/mmopuru/anaconda2/lib/python2.7/site-packages/PyGithub-1.34-py2.7.egg/github/__init__.py", line 37, in <module>
    from MainClass import Github, GithubIntegration
  File "/dbc/blr-dbc301/mmopuru/anaconda2/lib/python2.7/site-packages/PyGithub-1.34-py2.7.egg/github/MainClass.py", line 34, in <module>
    import jwt
ImportError: No module named jwt

Worked after installing it

**Comment by valeriocos** [comment]
Gitana does not rely directly on pyjwt (PyGitHub does) so it should not be included in the install_requires
