### ISSUE TITLE
Problem with unicode characters in branch names

### ISSUE THREAD

**Issue by jlcanovas** [SOM-Research/Gitana#3]
Hi,

I'm using Gitana to generate the database for https://github.com/rails/rails but the extractio process fails when extracting the data for one of the branches. This is the error I get:

```
origin/ಠ_ಠ,branch
Traceback (most recent call last):
  File "rails_launcher", line 23, in <module>
    main()
  File "rails_launcher", line 20, in main
    git2db()
  File "rails_launcher", line 16, in git2db
    g.git2db(SCHEMA, REPO_PATH, BEFORE_DATE, IMPORT_TYPE)
  File "/home/recerca/borge/Gitana/gitana.py", line 34, in git2db
    extractor.extract()
  File "/home/recerca/borge/Gitana/git2db.py", line 419, in extract
    self.get_info_contribution()
  File "/home/recerca/borge/Gitana/git2db.py", line 254, in get_info_contribution
    self.analyse_commits(commits, ref_name, repo_id)
  File "/home/recerca/borge/Gitana/git2db.py", line 386, in analyse_commits
    self.logger.info("Git2Db: analysing reference: " + ref + " -- commit " + str(commits.index(c)+1) + "/" + str(len(commits)) + " -- " + c.message)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe0 in position 36: ordinal not in range(128)

```

**Comment by valeriocos** [comment]
It seems there is a problem with the library used to get data from Git. I've just opened an issue there (https://github.com/gitpython-developers/GitPython/issues/515). 
For the time being, branch names with unicode/utf characters are ignored.
