### ISSUE TITLE
Add this repo as pip package and update beautifulsoup

### ISSUE THREAD

**Issue by gustawdaniel** [SOM-Research/Gitana#38]
I can't install it by pip

```
https://pypi.org/search/?q=gitana
```

Now I am installing by

```
git clone git@github.com:SOM-Research/Gitana.git
```

then in Gitana dir

```
python setup.py build
```

and

```
python setup.py install
```

but I have error

```
Writing /tmp/easy_install-2_gw0b9p/BeautifulSoup-3.2.2/setup.cfg
Running BeautifulSoup-3.2.2/setup.py -q bdist_egg --dist-dir /tmp/easy_install-2_gw0b9p/BeautifulSoup-3.2.2/egg-dist-tmp-8q5fk661
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/setuptools/sandbox.py", line 156, in save_modules
    yield saved
  File "/usr/lib/python3.10/site-packages/setuptools/sandbox.py", line 198, in setup_context
    yield
  File "/usr/lib/python3.10/site-packages/setuptools/sandbox.py", line 259, in run_setup
    _execfile(setup_script, ns)
  File "/usr/lib/python3.10/site-packages/setuptools/sandbox.py", line 45, in _execfile
    code = compile(script, filename, 'exec')
  File "/tmp/easy_install-2_gw0b9p/BeautifulSoup-3.2.2/setup.py", line 3
    "You're trying to run a very old release of Beautiful Soup under Python 3. This will not work."<>"Please use Beautiful Soup 4, available through the pip package 'beautifulsoup4'."
                                                                                                   ^^
SyntaxError: invalid syntax

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/builduser/pro/sm/code/Gitana/setup.py", line 6, in <module>
    setup(
  File "/usr/lib/python3.10/site-packages/setuptools/__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 148, in setup
    return run_commands(dist)
  File "/usr/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 163, in run_commands
    dist.run_commands()
  File "/usr/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 967, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.10/site-packages/setuptools/dist.py", line 1214, in run_command
    super().run_command(command)
  File "/usr/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.10/site-packages/setuptools/command/install.py", line 74, in run
    self.do_egg_install()
  File "/usr/lib/python3.10/site-packages/setuptools/command/install.py", line 131, in do_egg_install
    cmd.run(show_deprecation=False)
  File "/usr/lib/python3.10/site-packages/setuptools/command/easy_install.py", line 420, in run
    self.easy_install(spec, not self.no_deps)
  File "/usr/lib/python3.10/site-packages/setuptools/command/easy_install.py", line 662, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "/usr/lib/python3.10/site-packages/setuptools/command/easy_install.py", line 709, in install_item
    self.process_distribution(spec, dist, deps)
  File "/usr/lib/python3.10/site-packages/setuptools/command/easy_install.py", line 754, in process_distribution
    distros = WorkingSet([]).resolve(
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 789, in resolve
    dist = best[req.key] = env.best_match(
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1075, in best_match
    return self.obtain(req, installer)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1087, in obtain
    return installer(requirement)
  File "/usr/lib/python3.10/site-packages/setuptools/command/easy_install.py", line 681, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/usr/lib/python3.10/site-packages/setuptools/command/easy_install.py", line 707, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/usr/lib/python3.10/site-packages/setuptools/command/easy_install.py", line 900, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/usr/lib/python3.10/site-packages/setuptools/command/easy_install.py", line 1174, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/usr/lib/python3.10/site-packages/setuptools/command/easy_install.py", line 1158, in run_setup
    run_setup(setup_script, args)
  File "/usr/lib/python3.10/site-packages/setuptools/sandbox.py", line 249, in run_setup
    with setup_context(setup_dir):
  File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/lib/python3.10/site-packages/setuptools/sandbox.py", line 190, in setup_context
    with save_modules():
  File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/lib/python3.10/site-packages/setuptools/sandbox.py", line 169, in save_modules
    saved_exc.resume()
  File "/usr/lib/python3.10/site-packages/setuptools/sandbox.py", line 143, in resume
    raise exc.with_traceback(self._tb)
  File "/usr/lib/python3.10/site-packages/setuptools/sandbox.py", line 156, in save_modules
    yield saved
  File "/usr/lib/python3.10/site-packages/setuptools/sandbox.py", line 198, in setup_context
    yield
  File "/usr/lib/python3.10/site-packages/setuptools/sandbox.py", line 259, in run_setup
    _execfile(setup_script, ns)
  File "/usr/lib/python3.10/site-packages/setuptools/sandbox.py", line 45, in _execfile
    code = compile(script, filename, 'exec')
  File "/tmp/easy_install-2_gw0b9p/BeautifulSoup-3.2.2/setup.py", line 3
    "You're trying to run a very old release of Beautiful Soup under Python 3. This will not work."<>"Please use Beautiful Soup 4, available through the pip package 'beautifulsoup4'."
                                                                                                   ^^
SyntaxError: invalid syntax
```

**Comment by jlcanovas** [comment]
Hi @gustawdaniel, this tool has been archived and is not maintained anymore. Also, sorry to inform you that we cannot offer additional support either. 

The development status of our tools is declared [here](https://som-research.uoc.edu/research-tools/)
