### ISSUE TITLE
Error when extracting author information from Git

### ISSUE THREAD

**Issue by jlcanovas** [SOM-Research/Gitana#9]
I've experienced an error when extracting information from Git repositories with Gitana.

The particular error is:
```
Traceback (most recent call last):
  File "/home/recerca/Gitana/extractor/cvs/git/git2db_extract_reference.py", line 468, in extract
    self.get_info_contribution_in_reference(self.ref_name, self.repo_id, self.from_sha)
  File "/home/recerca/Gitana/extractor/cvs/git/git2db_extract_reference.py", line 299, in get_info_contribution_in_reference
    self.analyse_commits(commits, reference_name, repo_id)
  File "/home/recerca/Gitana/extractor/cvs/git/git2db_extract_reference.py", line 443, in analyse_commits
    self.analyse_commit(c, ref_id, repo_id)
  File "/home/recerca/Gitana/extractor/cvs/git/git2db_extract_reference.py", line 317, in analyse_commit
    author_name = self.querier.get_commit_property(commit, "author.name")
  File "/home/recerca/Gitana/extractor/cvs/git/querier_git.py", line 228, in get_commit_property
    found = commit.author.name
  File "/usr/lib64/python2.7/site-packages/gitdb/util.py", line 239, in __getattr__
    return object.__getattribute__(self, attr)
AttributeError: author
```

The issue appeared with the repos `Semantic-Org/Semantic-UI` (branch `origin-pre-release`) and `torvalds/linux` (most of the branches)

**Comment by valeriocos** [comment]
fixed in commit 38394deeb0f33e8b299288887ea565e0834b0371
